### PR TITLE
Form Api

### LINKED ISSUE #38: Form API
**Problem:** Users can't save or retrieve forms
**Solution:** Add some API endpoints and link them to frontend
**Description:**
We want a backend API that supports the following queries:
- Retrieve form progress
- Save form progress
- Anything else as deemed necessary
We also want to link these APIs with DynamicPOC.

The things we need to store:
- userId
- formValues
- questionHistory
- currentIndex
- currentQuestion
- currentAnswer

**Specs:**
- [x] Get form progress endpoint
  - [x] This should be a GET request with the query containing the user ID
  - [x] This should return a JSON containing either the form values or {error: string message}
- [x] Save form progress endpoint
  - [x] This should be a POST request with the body containing the form values and the user ID
  - [x] This should return a JSON containing either {success: true} or {error: string message}
- [x] Starting the form
  - [x] If the user has data saved in the database, set the appropriate starting question and formvalues
    - [x] User should start at the last-answered question
  - [x] If the user does not have data saved in the database, set starting question to first question and formvalues to an empty object
- [x] Saving the form
  - [x] When currentIndex changes, save everything to our database using the endpoint
- [x] Integrate with next-auth
  - [x] Determine userId based on next-auth storage
  - [x] provide this along with our requests!

**Expected Completion:** 2-3 weeks
**Resident Expert:** #engineering-support

### PR DESCRIPTION
**Pull request by dillydally414**
Closes #38 
Currently fails on production because it relies on next-auth, which is why we're going to merge into connect-both-ends (#50) instead of main

### CODE REVIEW

File: pages/api/form/save.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+export default async function handler(
+  req: NextApiRequest,
+  res: NextApiResponse
+) {
+  if (req.method !== 'POST') {
+    res.status(400).json({ error: 'Expected POST request' })
+    return
+  }
+
```
Comment (Nickdaco) [inline pages/api/form/save.ts:24]: what are const doc and const client returning?

**Review by Nickdaco — COMMENTED** [review]
Just kinda confused about the return not returning anything but that could just be something I didn't know. Other than that looks good

File: pages/api/form/save.ts (hunk 1 above)
Comment (dillydally414) [reply pages/api/form/save.ts:24]: `doc` is short for Document, which is what's stored in the database. So, we want to parse the request body into the form that our database expects it in (to make sure we're not including any additional unnecessary props)

Comment (dillydally414) [reply pages/api/form/save.ts:24]: `client` is the `MongoClient` which allows us to talk to the databases

File: pages/api/auth/[...nextauth].ts [hunk 2]
```diff
@@ -40,6 +40,20 @@ export default NextAuth({
       },
     }),
   ],
```
[the remark this answers is not in the document]
Comment (dillydally414) [reply pages/api/auth/[...nextauth].ts:42]: This is some janky next-auth stuff, but essentially we're saying with these two callbacks that when we authorize the user, we want to include an id field on the user - this will make the id accessible to us when storing and retrieving form values. This is the issue that is somewhat related to the issue you and Connie were facing, which we can discuss more at standup today, and I can also type up something in the Slack for reference

**Comment by dillydally414** [comment]
> Just kinda confused about the return not returning anything but that could just be something I didn't know. Other than that looks good

When a line just has `return` and nothing else, it's the same as when you do so in Java: `return;` 
- This gives the method a return type of `void`
- We use this in API endpoints to ensure that in error cases the endpoint stops handling input, otherwise the endpoint could error but still provide a valid response
- In NextJS endpoints, the valuable information is contained in a line looking something like this:
  - `res.status(num).json(obj)`
  - `num` is the [HTTP status](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) of the request
  - `obj` is an object containing information that we want to send back in the response - we use this to send error messages in error cases, or actual information in success cases. This information is then accessible to whoever hit the endpoint, and is the primary method of communication between the frontend and backend
